Removed initializing self.char and self.words in __init__ methods. Was causing:
...
    self.flatReviewContext = self.flatReviewContextClass(self)
  File "/usr/lib/python2.5/site-packages/orca/flat_review.py", line 657, in __init__
    while currentWordIndex < len(zone.words):
TypeError: object of type 'NoneType' has no len()

svn path=/trunk/; revision=3313