Fix for bug #435307 – OOo Calc output traceback for UnboundLocalError:
        * src/orca/scripts/StarOffice.py:
          Fix for bug #435307 – OOo Calc output traceback for
          UnboundLocalError: local variable 'focusRegion'
          referenced before assignment. Just needed to initialize
          focusRegion to None need the beginning of the
          _getBrailleRegionsForTableCellRow() method in the
          StarOffice script.

svn path=/trunk/; revision=2342